backend:
  name: github
  repo: tadweeralata-sketch/tdweer
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "إعدادات الموقع"
    files:
      - file: "data/settings.json"
        label: "بيانات الموقع"
        name: "settings"
        fields:
          - { label: "عدد الشراكات", name: "partners", widget: "string" }
          - { label: "عدد الأطنان", name: "tons", widget: "string" }
          - { label: "عدد السنوات", name: "years", widget: "string" }
          - { label: "عدد المتطوعين", name: "volunteers", widget: "string" }
          - { label: "رقم الجوال", name: "phone", widget: "string" }
          - { label: "الإيميل", name: "email", widget: "string" }
